### PR TITLE
update password for rocker/verse container

### PR DESCRIPTION
**Pull request by tatakof**
Added the (I guess) new password settings for the rocker/verse container.  
Great tutorial btw!

### CODE REVIEW

**Comment by jsta** [comment]
I think all the other open PRs suggest this change as well (#51,#52,#54,#55,#58). Do you have a preference for any particular implementation @franfram?

**Comment by neosanma** [comment]
oh, I didn't see the other PRs. My bad. 
hm, I'm new to docker (learning with your tutorial and a few other sources), so no. No preference really

**Comment by franfram** [comment]
Saludos desde Argentina. La próxima vez te escribo en español :)

**Comment by jsta** [comment]
Thanks for the PR! I've chosen to go with #55 as I think it catches all the places where a password is required.

**Pull request closed without merging**
