### PR TITLE
Merged template files directly into repo

### PR DESCRIPTION
**Pull request by marschmi**
Closes Issue #15.

Copied (and edited) necessary files from karthik/dcTemplate and updates YAML headers in lesson 0 through 4.

WARNING: karthik/dcTemplate is under a GPL-3 license.  @bsmith89 and I think this might be incompatible with the license (or intended license) for this lesson.

### CODE REVIEW

**Comment by katieannemills** [comment]
This is relevant to #12 as well; @karthik, can you advise on the licensing issue here? Thanks all!

**Comment by katieannemills** [comment]
Actually, now that I look at it, I don't see a license on this lesson yet. SWC material is [CC-BY 4.0](https://github.com/swcarpentry/git-novice/blob/gh-pages/LICENSE.md) - @HeidiSeibold, is that the intention here?

**Comment by bsmith89** [comment]
We also just realized that we were wrong to delete the files in `stylesheets/` (`styles.css`, which we replaced and `github-light.css`) since they're used by `index.html`.

What should we name the stylesheet from [dcTemplate](github.com/karthik/dcTemplate)?

**Comment by katieannemills** [comment]
ping @HeidiSeibold @ttimbers @lmguzman or anyone who knows more about knitr / rmd than me :)

**Comment by HeidiSeibold** [comment]
Sorry, I just saw this pull request now. I have no idea about css and co so it would be great if someone else could tell me if this should be accepted.

**Comment by HeidiSeibold** [comment]
Any updates on this?

**Comment by jsta** [comment]
Cleaning up old/stale issues and PRs. Happy to revisit if someone gives the word.

**Pull request closed without merging**
